name: LLM-KC
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - jupyter
  - pytorch::pytorch  # Specifies the 'pytorch' package from the 'pytorch' channel
  - pytorch::torchvision
  - pytorch::torchaudio
  - tqdm
  - matplotlib
  - seaborn
  - pandas
  - pyarrow
  - scikit-learn
  - h5py
  - pip:
    - transformers