name: my-huggingface-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - jupyter
  - pytorch::pytorch  # Specifies the 'pytorch' package from the 'pytorch' channel
  - pytorch::torchvision
  - pytorch::torchaudio
  - tqdm
  - pip:
    - transformers